/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logicaaeronave;

import javax.swing.JOptionPane;

/**
 *
 * @author Yan53961666
 */
public class aeronaveLogica extends javax.swing.JFrame {

    /**
     * Creates new form aeronaveLogica
     */
    public aeronaveLogica() {
        initComponents();
        txtLigar.setText("não");
        txtAttDecolar.setText("não");
        txtChecklist.setText("não");
        txtSubir.setText("não");
        txtAttDescer.setText("não");
        txtDescer.setText("não");
        txtDesligar.setText("não");
        situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        btnLigar = new javax.swing.JButton();
        btnAttDecolar = new javax.swing.JButton();
        btnCheckList = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnAttDescer = new javax.swing.JButton();
        btnDescer = new javax.swing.JButton();
        btnDesligar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        situacaoAeronave = new javax.swing.JTextArea();
        txtLigar = new javax.swing.JTextField();
        txtAttDecolar = new javax.swing.JTextField();
        txtChecklist = new javax.swing.JTextField();
        txtSubir = new javax.swing.JTextField();
        txtAttDescer = new javax.swing.JTextField();
        txtDescer = new javax.swing.JTextField();
        txtDesligar = new javax.swing.JTextField();

        jTextField4.setText("desligada");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLigar.setText("Ligar Aeronave");
        btnLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLigarMouseClicked(evt);
            }
        });
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });

        btnAttDecolar.setText("Pedir Autorização Decolar");
        btnAttDecolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAttDecolarMouseClicked(evt);
            }
        });

        btnCheckList.setText("Verificar Check List");
        btnCheckList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckListMouseClicked(evt);
            }
        });

        btnSubir.setText("Subir Aeroanve");
        btnSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubirMouseClicked(evt);
            }
        });
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        btnAttDescer.setText("Pedir Autorização Descer");
        btnAttDescer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAttDescerMouseClicked(evt);
            }
        });

        btnDescer.setText("Descer Aeronave");
        btnDescer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescerMouseClicked(evt);
            }
        });

        btnDesligar.setText("Desligar Aeronave");
        btnDesligar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesligarMouseClicked(evt);
            }
        });

        situacaoAeronave.setColumns(20);
        situacaoAeronave.setRows(5);
        jScrollPane1.setViewportView(situacaoAeronave);

        txtLigar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLigar.setText("não");

        txtAttDecolar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAttDecolar.setText("não");
        txtAttDecolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttDecolarActionPerformed(evt);
            }
        });

        txtChecklist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChecklist.setText("não");
        txtChecklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChecklistActionPerformed(evt);
            }
        });

        txtSubir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubir.setText("não");

        txtAttDescer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAttDescer.setText("não");

        txtDescer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescer.setText("não");

        txtDesligar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesligar.setText("não");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAttDecolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLigar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAttDescer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDescer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDesligar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAttDescer)
                    .addComponent(txtDescer)
                    .addComponent(txtDesligar)
                    .addComponent(txtLigar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtAttDecolar)
                    .addComponent(txtChecklist)
                    .addComponent(txtSubir))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLigar)
                            .addComponent(txtLigar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAttDecolar)
                            .addComponent(txtAttDecolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckList)
                            .addComponent(txtChecklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubir)
                            .addComponent(txtSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAttDescer)
                            .addComponent(txtAttDescer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDescer)
                            .addComponent(txtDescer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDesligar)
                            .addComponent(txtDesligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLigarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigarMouseClicked
        if(txtChecklist.getText().equals("sim" )){
            txtLigar.setText("sim");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Você precisa fazer o checklist antes!");
        }
    }//GEN-LAST:event_btnLigarMouseClicked

    private void txtAttDecolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttDecolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttDecolarActionPerformed

    private void txtChecklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChecklistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChecklistActionPerformed

    private void btnCheckListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckListMouseClicked
        if(txtChecklist.getText().equals("não")){
            txtChecklist.setText("sim");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        }
    }//GEN-LAST:event_btnCheckListMouseClicked

    private void btnAttDecolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttDecolarMouseClicked
        if(txtAttDecolar.getText().equals("não")){
            txtAttDecolar.setText("sim");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        }
    }//GEN-LAST:event_btnAttDecolarMouseClicked

    private void btnSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseClicked
        if(txtAttDecolar.getText().equals("sim")){
            txtSubir.setText("sim");
             situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Você precisa pedir autorização para subir antes!");
        }
    }//GEN-LAST:event_btnSubirMouseClicked

    private void btnAttDescerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttDescerMouseClicked
        if(txtAttDescer.getText().equals("não")){
            txtAttDescer.setText("sim");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        }
    }//GEN-LAST:event_btnAttDescerMouseClicked

    private void btnDescerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescerMouseClicked
        if(txtAttDescer.getText().equals("sim")){
            txtDescer.setText("sim");
            txtSubir.setText("não");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Você precisa pedir autorização para descer antes!");
        }
    }//GEN-LAST:event_btnDescerMouseClicked

    private void btnDesligarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesligarMouseClicked
        if(txtLigar.getText().equals("sim")){
            txtDesligar.setText("sim");
            txtLigar.setText("não");
            situacaoAeronave.setText("Aeronave ligada: " + txtLigar.getText() + "\n" 
                + "Aeronave tem autorização subir: "  +  txtAttDecolar.getText() + "\n"
                + "Aeronave tem autorização descer: "  +  txtAttDescer.getText() + "\n" 
                +  "Aeronave fez checklist: " + txtChecklist.getText() + "\n"
                +  "Subir: " + txtSubir.getText() + "\n"
                + "Descer: " + txtDescer.getText());
        } else {
            JOptionPane.showMessageDialog(null, "A aeronave precisa estar ligada antes!");
        }
    }//GEN-LAST:event_btnDesligarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aeronaveLogica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttDecolar;
    private javax.swing.JButton btnAttDescer;
    private javax.swing.JButton btnCheckList;
    private javax.swing.JButton btnDescer;
    private javax.swing.JButton btnDesligar;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea situacaoAeronave;
    private javax.swing.JTextField txtAttDecolar;
    private javax.swing.JTextField txtAttDescer;
    private javax.swing.JTextField txtChecklist;
    private javax.swing.JTextField txtDescer;
    private javax.swing.JTextField txtDesligar;
    private javax.swing.JTextField txtLigar;
    private javax.swing.JTextField txtSubir;
    // End of variables declaration//GEN-END:variables
}
