/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raquetemosquito;

import javax.swing.JOptionPane;

/**
 *
 * @author Yan53961666
 */
public class mataMosquito extends javax.swing.JFrame {
    private int num;
    public mataMosquito() {
        num = 0;
        initComponents();
        txtCarregar.setText("não");
        txtLigar.setText("não");
        txtUsar.setText("não");
        statusRaquete.setText("Carregar raquete: " + txtCarregar.getText() + "\n"
        + "Ligar raquete: " + txtLigar.getText() + "\n"
        + "Usar raquete: " + txtUsar.getText() + "\n"
        + "Bateria: " + num);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statusRaquete = new javax.swing.JTextArea();
        btnCarregar = new javax.swing.JButton();
        btnUsar = new javax.swing.JButton();
        btnLigar = new javax.swing.JButton();
        txtCarregar = new javax.swing.JTextField();
        txtLigar = new javax.swing.JTextField();
        txtUsar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusRaquete.setColumns(20);
        statusRaquete.setRows(5);
        jScrollPane1.setViewportView(statusRaquete);

        btnCarregar.setText("Carregar Raquete");
        btnCarregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarregarMouseClicked(evt);
            }
        });
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        btnUsar.setText("Usar Raquete");
        btnUsar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsarMouseClicked(evt);
            }
        });

        btnLigar.setText("Ligar Raquete");
        btnLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLigarMouseClicked(evt);
            }
        });
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });

        txtCarregar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCarregar.setText("não");
        txtCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarregarActionPerformed(evt);
            }
        });

        txtLigar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLigar.setText("não");
        txtLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLigarActionPerformed(evt);
            }
        });

        txtUsar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsar.setText("não");
        txtUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarregar)
                    .addComponent(txtLigar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtUsar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarregar)
                            .addComponent(txtCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLigar)
                            .addComponent(txtLigar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUsar)
                            .addComponent(txtUsar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLigarActionPerformed

    private void txtCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarregarActionPerformed

    private void txtLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLigarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLigarActionPerformed

    private void txtUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsarActionPerformed

    private void btnCarregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarregarMouseClicked
          if(txtCarregar.getText().equals("não") && num <= 0){
            txtCarregar.setText("sim");
                do{
                    num = num + 10;
                } while (num <= 100);
                
            statusRaquete.setText("Carregar raquete: " + txtCarregar.getText() + "\n"
                + "Ligar raquete: " + txtLigar.getText() + "\n"
                + "Usar raquete: " + txtUsar.getText() + "\n"
                + "Bateria: " + num);
        } else{
            JOptionPane.showMessageDialog(null, "Bateria cheia!");
        }
    }//GEN-LAST:event_btnCarregarMouseClicked

    private void btnLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigarMouseClicked

        if(txtLigar.getText().equals("não")){
            txtLigar.setText("sim");
            statusRaquete.setText("Carregar raquete: " + txtCarregar.getText() + "\n"
            + "Ligar raquete: " + txtLigar.getText() + "\n"
            + "Usar raquete: " + txtUsar.getText() + "\n"
            + "Bateria: " + num);
        } else {
            txtLigar.setText("não");
            statusRaquete.setText("Carregar raquete: " + txtCarregar.getText() + "\n"
            + "Ligar raquete: " + txtLigar.getText() + "\n"
            + "Usar raquete: " + txtUsar.getText() + "\n"
            + "Bateria: " + num);
        }
    }//GEN-LAST:event_btnLigarMouseClicked

    private void btnUsarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsarMouseClicked

        if(txtLigar.getText().equals("sim") && num > 0){
            txtUsar.setText("sim");
                do{
                        num = num - 10;
                    } while (num > 0);
            statusRaquete.setText("Carregar raquete: " + txtCarregar.getText() + "\n"
            + "Ligar raquete: " + txtLigar.getText() + "\n"
            + "Usar raquete: " + txtUsar.getText() + "\n"
            + "Bateria: " + num);
        } else if(num == 0){
            JOptionPane.showMessageDialog(null, "Bateria vazia!");
        }
    }//GEN-LAST:event_btnUsarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mataMosquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mataMosquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mataMosquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mataMosquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mataMosquito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnUsar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea statusRaquete;
    private javax.swing.JTextField txtCarregar;
    private javax.swing.JTextField txtLigar;
    private javax.swing.JTextField txtUsar;
    // End of variables declaration//GEN-END:variables
}
