/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package calculadoraradiobtn;

/**
 *
 * @author Yan53961666
 */
public class CalculadoraSimples extends javax.swing.JInternalFrame {

    double result;
    public CalculadoraSimples() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpCalculadora = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rSoma = new javax.swing.JRadioButton();
        rSubtracao = new javax.swing.JRadioButton();
        rDivisao = new javax.swing.JRadioButton();
        rMultiplicacao = new javax.swing.JRadioButton();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCalculo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("CALCULADORA SIMPLES");

        gpCalculadora.add(rSoma);
        rSoma.setText("Soma");
        rSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSomaActionPerformed(evt);
            }
        });

        gpCalculadora.add(rSubtracao);
        rSubtracao.setText("Subtração");
        rSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSubtracaoActionPerformed(evt);
            }
        });

        gpCalculadora.add(rDivisao);
        rDivisao.setText("Divisão");

        gpCalculadora.add(rMultiplicacao);
        rMultiplicacao.setText("Multiplicação");
        rMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMultiplicacaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Primeiro número:");

        jLabel3.setText("Segundo número:");

        jLabel4.setText("Resultado:");

        btnCalculo.setText("CALCULAR");
        btnCalculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculoMouseClicked(evt);
            }
        });
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnCalculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(rSoma)
                        .addGap(18, 18, 18)
                        .addComponent(rSubtracao)
                        .addGap(18, 18, 18)
                        .addComponent(rDivisao)
                        .addGap(18, 18, 18)
                        .addComponent(rMultiplicacao)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSoma)
                    .addComponent(rSubtracao)
                    .addComponent(rDivisao)
                    .addComponent(rMultiplicacao))
                .addGap(57, 57, 57)
                .addComponent(btnCalculo)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSomaActionPerformed

    private void rSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSubtracaoActionPerformed

    private void rMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rMultiplicacaoActionPerformed

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculoActionPerformed

    private void btnCalculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculoMouseClicked
        double n1 = Double.parseDouble(num1.getText());
        double n2 = Double.parseDouble(num2.getText());
 
        if(rSoma.isSelected()){
            result = n1 + n2;
        } else if(rSubtracao.isSelected()){
            result = n1 - n2;
        } else if(rDivisao.isSelected()){
            result = n1 / n2;
        } else if(rMultiplicacao.isSelected()){
            result = n1 * n2;
        }
        resultado.setText(String.valueOf(result));
    }//GEN-LAST:event_btnCalculoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo;
    private javax.swing.ButtonGroup gpCalculadora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JRadioButton rDivisao;
    private javax.swing.JRadioButton rMultiplicacao;
    private javax.swing.JRadioButton rSoma;
    private javax.swing.JRadioButton rSubtracao;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
